namespace-ee/react-calendar-timeline

src/lib/Timeline.jsx
Hi, as far as i know, .bind(this) !== .bind(this), so your handlers will never be de-attached. That cause memory leak in my application.
This PR eliminate this issue.
BR
=> Fixed memory leak when attach\deattach touch[start,move,end] listeners

README.md, src/lib/Timeline.jsx, src/lib/items/Item.jsx
Sometimes it can be useful to have original event object inside handler method arguments. 
For example to get coordinates of the mouse cursor on rightClick / doubleClick and open custom context menu at the appropriate place.
In this PR I added this just for simple mouse events. Probably in future, it will make sense to do the same for interact.js events (for such handlers like onItemMove, onItemResize).
=> [Item][Events] Send original event object to handler function arguments for mouse events

src/lib/items/Item.jsx
Fix to #24 issue.
In `resizeTimeSnap` method we consider `endTime` which is indivisible part of `itemTimeEnd` to `dragSnap` property. So the item length will always increase or decrease equally on `dragSnap` property and will save the correct time.
Also added `considerOffset` parameter to `dragTimeSnap` method to fix item drag behavior.
I've tested this with different time zones and `dragSnap` values and it works for me.
=> [Item][dragSnap] Fixed item move and resize behavior when dragSnap property set

src/lib/utils.js
Avoid comparing items that have not been positioned yet (item.dimensions.top is null).  I am sure that was the original intent, but item.top was being checked by mistake.
=> Fix typo collision detection in stack()

src/lib/items/Item.js
Hey, the interactjs cursor styling is unnecessary since timeline calendar will already take care of it. Also there is currently a bug with interactjs cursors where it gets stuck on html tag. https://github.com/taye/interact.js/issues/497
=> Disable cursor style by interactjs

src/lib/Timeline.js
Because setState runs at the end of updateScrollCanvas and applies the update asynchronously, updateDimensions computes using stale state.  When visibleTimeStart and visibleTimeEnd are specified this causes the items to be drawn in the wrong place occasionally when scrolling.  This update fixes it.  Since updateScrollCanvas already updates the item dimensions the call to updateDimensions is redundant anyway.
=> Avoid updating updateDimensions right after updateScrollCanvas

src/lib/Timeline.js
This fixes issue #39 
also fixes the FIXME issue "currently when the component creates a scroll the scrollbar is not used in the initial width calculation, resizing fixes this"
=> Calculate width when we receive sidebar width property

README.md, index.html, src/lib/Timeline.js, src/lib/items/Items.js
If you pass the prop `selected=['id1','id2']` to the timeline component the default behaviour of selecting only one item at a time is overwritten. From then on you have to manage the selected items yourself within the `onItemSelect` handler and pass the new id's to the selected props again. This enables you to have multiple items selected. This change is not breaking the existing behaviour because if `selected` is not set nothing changes for the user.
=> ADD: Option for multiple selected Items

src/lib/Timeline.js, src/lib/__tests__/index.js
If the Timeline had no grups;
```jsx
<Timeline
groups={[]}
items={items}
defaultTimeStart={moment('1995-12-25').add(-12, 'hour')}
defaultTimeEnd={moment('1995-12-25').add(12, 'hour')}
/>
```
the component threw a error. I handled this case in `stackItems` because this gets executed already in the constructor. Someone a better idea where to handle it?
=> FIX: renders with empty groups-array

package.json, src/lib/Timeline.js
Now uses element-resize-detector for resize detection.
This can be changed back to 'window' resize eventListener with property `resizeDetectorMethod ="window"`.
Benefit of this is that when something resizes Timeline component for example side scroll bar, we could detect this change and call resize for the component.
=> Add support for element-resize-detector

README.md
is there a reason why in the `index.js` the additional props are wrapped in `itemProps`? It's one way right? But could also be passed in as unwrapped additional attribute? At least it works for me.
```jsx
let items = [
{
id: 1,
group: 1,
title: 'Title',
tip: 'additional information',  // <<<< like here
...
}
]
```
=> ADD: example for itemRenderer and groupRenderer

src/lib/__tests__/index.js, src/lib/utils.js
```js
let groups = [
{
id: 1,
title: 'Title'
}
]
let items = [
{
...
group: -1, // here is the problem!
title: 'Title'
}
]
```
=> FIX: if items with no corresponding group

src/lib/__tests__/index.js, src/lib/utils.js
The items from the first group don't get rendered properly, because they have an order of 0 and the getGroupedItems method only does a falsy comparison
=> check group order for undefined in getGroupedItems

.gitignore, src/lib/Timeline.js, src/lib/__tests__/utils-test.js, src/lib/items/Item.js, src/lib/items/Items.js, src/lib/utils.js
I'm working on a function to have multiple Items drag at the same time. But for that I don't wanna mess with the `calculateDimensions`. Therefore I had a look at it and worked on some simplification and made it testable. 
_The following things were done in this PR:_
* no need to filter by valid dimension after `calculateDimensions`. Only add  if dimension is valid (`reduce instead` of `map` & `filter`)
* everything that is not pure calculation is taken out of the function so we don't need the keys in the `calculateDimensions`
* no round trips where we pass values in just go give it back then (like for `stack`)
* added tests
Beside the `lineHeight` I didn't do anything to the general handling. The `lineHeight` was just adjusted because we don't need to save it in each calculation. 
Over …
=> Refactoring of calculateDimensions

package.json
According to [this page](https://www.reddit.com/r/javascript/comments/5jwg9c/confused_about_fields_module_and_jsnextmain_in/), the standard way to describe a `jsnext` entry point is through the `module` field in `package.json`, not `jsnext:main`. Updating to that
=> rename jsnext:main to module

src/lib/Timeline.js, src/lib/layout/Header.js, src/lib/layout/Sidebar.js
Hi, here you'll find my stickyOffset enhancement, see Issue #135 with some screenshots.
The motivation is the following: I have a Bootstrap Navbar scrolling up. At a certain point the Navbar is fixed in its position with a certain height. I want the calendar header scroll up and to be sticky up to the height of the Navbar.
=> API has to be adapted, below prop "fixedHeader" a new prop "stickyOffset": 
When fixedHeader is sticky (default) the stickyOffset value (default: 0) defines the distance from top where the header is fixed.
BR Kai
=> Added stickyOffset

src/lib/utils.js
When you scroll a page with the timeline, the onCanvasClick incorrectly determines the group/row for many browsers (Edge, Firefox, and Chrome 61). These browsers always return 0 for the body element's scrollTop property. Since the element.offsetParent bubbles up to the body element rather than the actual scrolling element, the onCanvasClick returns row/group as if the page was not scrolled. I mainly use chrome and didn't notice the issue till the latest chrome update.
Ideally offsetParent would return the scrolling element as the top level parent, but this was a quick solution that fixed the issue I was having. There may be better ways to solve. I tried to make it fall back to previous behavior if it didn't meet specific requirements.
=> Fix onCanvasClick when scrolled

src/lib/utils.js
fixes:
```
Uncaught TypeError: e.className.split is not a function
at y (utils.js:360)
at t.value (Timeline.js:641)
at t.D.scrollAreaClick (Timeline.js:1551)
```
e.g. when doing mouseUp on SVGElement child
see https://developer.mozilla.org/en-US/docs/Web/API/Element/className#Notes
> It is better to get/set the className of an element using Element.getAttribute and Element.setAttribute if you are dealing with SVG elements
=> use .getAttribute('class') instead of .className

CHANGELOG.md, demo/app/demo-main/index.js, src/lib/Timeline.js
Fixes https://github.com/namespace-ee/react-calendar-timeline/issues/227
=> Fix - incorrect time on onItem* events if outer timeline container has padding

src/lib/items/Items.js
item.selected is declared with propTypes to be a boolean. When I supply my own selected prop I get a proptype warning. This is because the isSelected function in the Items component returns a boolean only if there is no selected prop, the problem is that if an array of ids is supplied it returns selected.find() which will return what was found and not the boolean expected by Item.
Using includes instead  will return a boolean value
=> items isSelected to return boolean

CHANGELOG.md, README.md, src/lib/Timeline.js
https://github.com/namespace-ee/react-calendar-timeline/issues/236
=> 236 - fixes issue where clicking/double clicking header calls canvas click/doubleClick

CHANGELOG.md, src/lib/Timeline.js
https://github.com/namespace-ee/react-calendar-timeline/issues/266
=> Use left property of rect returned from getBoundingClientRect

demo/app/demo-main/index.js, src/lib/Timeline.js
Bandaid to fix issue when dragging item on canvas.  This was a regression related to removing references to header height.  topOffset needs to be a function of container top, scroll offset AND header height.  This is because dragging item event looks at pageY, not the scroll element.
=> Fix - Dragging items and canvas click

CHANGELOG.md, README.md, package.json, src/lib/items/Item.js, webpack.config.js, yarn.lock
https://github.com/namespace-ee/react-calendar-timeline/issues/297
* Move interactjs to peerDependency (breaking change)
=> Move interactjs to peerDependency, up version to fix #297

CHANGELOG.md, README.md, package.json, src/lib/Timeline.js
Currently, only visibleTimeStart/End and canvas width are being passed to the timelineContext prop in itemRenderer. Let's pass canvas times too.
=> Pass Canvas time values in timelineContext

CHANGELOG.md, README.md, package.json, src/lib/Timeline.js, src/lib/items/Item.js
Without issue
Allow to specify custom style for the item element. For example, it can be a different background color for each item (driven by some business logic, etc). Strange that it wasn't implemented before. it is so useful feature.
As well as, provide prop `selected` to the itemRenderer. I have a few cases when I need to know inside the item content does it selected or no. For example, I prefer to render some advanced information inside selected items. Or some way react to this prop in the child component lifecycle - open a modal, or send a request at last.
=> Support Item prop style. Provide prop selected to itemRenderer

CHANGELOG.md, __tests__/utils/calendar/calculate-dimensions.js, src/lib/Timeline.js, src/lib/utility/calendar.js
None.
This is a refactoring of calculate dimensions to simplify the logic. These changes also bound the width of an item to the width of the canvas and set a floor on the left value of an item.
These changes might also fix https://github.com/namespace-ee/react-calendar-timeline/issues/292
=> Simplify calculate-dimensions/bound item width and left

CHANGELOG.md, src/lib/Timeline.js, src/lib/markers/MarkerCanvas.js, src/lib/markers/implementations/shared.js
#378 
#383 
Move `MarkerCanvas` up to wrap all timeline elements in canvas (items, groups, etc)
=> Fix issues related to position of MarkerCanvas

examples/README.md
As asked in https://github.com/namespace-ee/react-calendar-timeline/issues/372#issuecomment-417103151 I provided an example. 
Add sandbox which shows how to use `scrollRef` to programmatically scroll.
=> Add example for scrollRef

src/lib/Timeline.scss, src/lib/layout/TimelineElementsHeader.js
For most of CSS classes prefix `rct` is used to avoid styling issues. Two children of Header `top-header` and `top-header` currently are missing this prefix which this PR adds.
=> use 'rct' prefix for class names of Header children

src/lib/utility/calendar.js
#455 
Forces canvas to re-draw when the zoom level changes.
On MacOS the zoom level changes a small amount on zoom. This causes the timeline items to not update and appear to 'drift' on the timeline.
=> Fix to force re-render on zoom change

CHANGELOG.md, demo/app/demo-tree-groups/index.js, demo/app/generate-fake-data.js, package.json, src/lib/Timeline.js, src/lib/default-config.js
https://github.com/namespace-ee/react-calendar-timeline/issues/442#issue-367851639
The fix involves introducing a new key in the Timeline keys object called `groupLabelKey`, which is defaulted to `title`. This will preserve existing functionality. When the `groupLabelKey` is specified to point to a string attribute of the group object, that is used to render the text in the InfoLabel.
This allows the developer to split what is used to render the Sidebar with what is used to render the InfoLabel.
=> Added group label key to fix label info onDrag

src/lib/layout/Sidebar.js
https://github.com/namespace-ee/react-calendar-timeline/issues/478
Changed equality comparison of groupHeights to use arraysEquals utility function instead. This will prevent re-render's of sidebar when groupHeights doesn't change.
Also moved arraysEqual checks after the equality comparisons to take advantage of short circuiting.
=> Fix sidebar re-render when groupHeights do not change

README.md
This PR does not relate to any issue as it's merely a documentation fix.
Fixes invalid JavaScript syntax, i.a. removes explicit return statements from [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#Function_body) with concise body as show in the examples.
=> docs: correct invalid JavaScript syntax in examples

README.md
There is no issue related to this PR - I'm submitting this PR to make it easier for anyone who sees the README.md that `react-calendar-timeline` is MIT licensed.
Not sure if I should update CHANGELOG.md for this small change? Happy to do it though if needed.
---
Thanks for all the work with this repo 💯
=> docs: adding link to LICENSE.md to README.md

__tests__/components/Markers/TimelineMarkers.test.js, src/lib/markers/TimelineMarkersContext.js
**524**
[Markers don't get unsubscribed after being hidden, if date has previously changed](https://github.com/namespace-ee/react-calendar-timeline/issues/524)
Filtering Markers by Id instead of just the whole object, as if you change the marker date couple times, the marker won't be the same object on unsubscribe.
**Demo **
Before
After
=> TimelineMarkers: Unsubscribing markers correctly when hidden

README.md
This is not related to an issue as it's purely a documentation fix.
This PR adds missing links for `react` and `react-native` and fixes minor spelling mistakes.
=> docs: fix minor spelling mistakes + update links for react and react-native

README.md
**Issue Number & Overview**
Not related to an issue, but the Readme is getting quite long, so I thought that it'd be good to table of contents so that it's easier to navigate the documentation :-)
=> docs: add contents section to improve navigating the readme

CHANGELOG.md, __tests__/components/Headers/TimelineHeader.test.js, package.json, src/lib/headers/TimelineHeaders.js
566
Use [`classnames` utility](https://github.com/JedWatson/classnames) to build lists of classnames, automatically excluding falsey values.
Result:
Commits were separated for clarity but are intended to be squashed into one.
**Alternative Approach**
If the project does not want the new dependency on `classnames`, we could achieve the same exclusion of falsey values using just native JS, something like:
```jsx
const classnames = (...names) => names.filter(Boolean).join(" ");
className={classnames('rct-header-root', this.props.className)}
```
(Actually, after I write that out, I may like it better since the `classnames` package does a lot this project probably doesn't need. Happy to change it.)
=> Undefined classnames in TimelineHeaders

CHANGELOG.md, package.json, yarn.lock
Issue #598 
Moves `classnames` to a production dependency
=> fix: classnames should be a prod dependency, not dev

__tests__/components/GroupRow/GroupRows.test.js, __tests__/components/Sidebar/Sidebar.test.js, src/lib/Timeline.scss, src/lib/layout/Sidebar.js, src/lib/row/GroupRows.js
**609**
[Items get misaligned from their row on browser scaling](https://github.com/namespace-ee/react-calendar-timeline/issues/609)
Items get misaligned from their rows as the timeline gets scrolled down when the browser scale is different than 100%
This is happening because on some zoom levels, the row is `30px` height (default value), and for other % it gets to `29.98px`.
This undesired behaviour is fixable by replacing `content-box` by `border-box` for **box-sizing** property on `.rct-sidebar-row` and `.rct-horizontal-lines`.
Now, the subtraction of `1px` from the height in `GroupRow` and `Sidebar` components is no longer needed as the `border-bottom` is included in the element dimensions.
**Demo**
=> Fixing row height on browser scaling

CHANGELOG.md, README.md
https://github.com/namespace-ee/react-calendar-timeline/issues/473
The `stackItems` option does nothing if the timeline objects use native JS Date objects. Instead, they must be milliseconds or Moment timestamps.
This PR updates the documentation to reflect the above.
=> Clarify stackItems option timestamp requirements

README.md
The documentation suggests onCanvasDoubleClick and onCanvasContextMenu have a group parameter as an object, which is different from all of the item events which use item ID. Fortunately the code does the right thing and it is actually the group ID.
#705 
Fixes the documented parameters.
=> Fix docs for onCanvasDoubleClick and onCanvasContextMenu

src/lib/utility/dom-helpers.js
**Issue Number 703**
[issue](https://github.com/namespace-ee/react-calendar-timeline/issues/703)
This Pr changes `getSumOffset` to stop recursing if offsetParent is null. This prevents crashes in cases where some ancestor has `position: fixed`
=> check for offsetParent before using

CHANGELOG.md, README.md, src/lib/Timeline.js
Fixes #682.
Adds a `className` prop to the top-level `Timeline` component to override the `react-calendar-timeline` class.
=> Add className prop to top-level Timeline

package.json
#748 
Update create-react-context v0.3.0 because the previous v.2.3 include text in the license file which could block its usage as an open-source lib. Those text are removed from create-react-context v0.3.0.
=> update create-react-context version to v0.3.0

CHANGELOG.md, src/lib/columns/Columns.js
Fixes injecting custom class names for vertical lines spanning over a period of time longer than day (eg. month)
Right now if we want to inject custom class name for vertical line spanning month it's class names end up corrupted. If I'll return `timeline-month` class from `verticalLineClassNamesForTime` function I'll end up with vertical line element: `<div class="rct-vltimeline-month">` instead of `<div class="rct-vl timeline-month">`
=> Fix injecting custom class names for vertical lines

CHANGELOG.md, README.md, demo/app/demo-main/index.js, src/lib/Timeline.js
#655 
I added `unit` argument to `onZoom` and `onTimeChange` callbacks,  as discussed in #655.
=> Add unit argument to onZoom and onTimeChange callbacks

vite.config.mts
Fixes #937 
Would be awesome for having a quick merge, because no breaking change, no problem, just removes overhead, reduce bundle size, and also provides a fix.
Optimizes bundeling sizes, because at the moment react/jsx-runtime is being bundled unnecessary leading to a overhead in production, by externalizing react/jsx-runtime and also for the future react-dom/client
=> build: externalize react/jsx-runtime and react-dom/client

src/lib/utility/calendar.tsx
Fixes #946
https://github.com/namespace-ee/react-calendar-timeline/issues/946
Rather than updating the dayjs object, dayjs.set() returns a copy of it. This ensures the time variable is update to use the offset.
=> Issue 946: reassign adjusted value to time

src/lib/utility/calendar.js
Issue:
Currently if there is a daylight saving, the days after the daylight saving starts at 1am.
Fix:
Always make sure when iterating that it start at the beginning of the day.
=> fix start and end of day when there is daylight saving

src/lib/scroll/ScrollElement.tsx
The event handler onCanvasClick would not trigger on some mobile devices due to the ScrollElement's handleTouchStart calling e.preventDefault(). Tested on iOS Safari and Android Firefox. 
This PR refactors ScrollElement's event handling by replacing traditional mouse and touch events with pointer events.
=> Refactor ScrollElement to support pointer events
