modules/lib/Timeline.js
modules/lib/items/Item.js
src/lib/Timeline.jsx
src/lib/items/Item.jsx

Allow doubleclick listener on canvas. When you double click on the canvas the click handler is given the time position where the click happens and the group. Ideally it allows creating of new items to the click position.

Add doubleclick handler on canvas

---

src/lib/lines/VerticalLines.jsx

The issue: http://dl2.joxi.net/drive/2016/04/10/0007/3617/495137/37/42faf332fd.png

[VerticalLines] Fixed first line top position, if line height has been changed

---

src/lib/Timeline.jsx

#6 
I've faced the same issue when was trying to add dynamically new items to the timeline.
This made a trick for me. Hopefully, this will also fix the issue above

[Timeline] Update dimensionItems when [items] or [groups] props are changing.

---

README.md
index.html
src/lib/Timeline.jsx
src/lib/items/Item.jsx
src/lib/items/Items.jsx

In our project we need to overwrite the context menu on an item. 
Probably it can be useful for somebody else :)

[Item] Added property for handling contextMenu event on item

---

src/lib/Timeline.jsx

Hi!
We encounter a problem with widget resizing, if we render it inside a DIV element.
This patch should fix the problem.

fix resizing

---

index.html

That's basically everything thats needed for IE11 support. Without it IE11 won't display anything.

add polyfill on demo for IE11 support

---

src/lib/items/Items.js

Closes #62
Edit: leave comments if I have to rebuild and bump the version in this PR

Fix canResize prop for Item.

---

README.md

only changes on the readme therefor no version bump

FIX: Typo in readme. no coffee-beans here

---

src/lib/utils.js

I think we don't need that function anymore. Right?

MOD: remove createGradientPattern

---

CHANGELOG.md

Added 0.14.2 with the changes for prop-types.
Also some of the compare links are broken, so I added it for direct commits. Just fyi! Thanks for the changes @mariusandra.

Update CHANGELOG.md to include 0.14.2

---

src/lib/Timeline.scss

See my [code example](https://www.webpackbin.com/bins/-KnBowMj956_Hrkr7UGE) to see the problem with the haeder

FIX: Problem with overflow in header

---

README.md

By answering https://github.com/namespace-ee/react-calendar-timeline/issues/79 I found out about the key-modifiers to navigate within the timeline

ADD: Interaction description

---

src/lib/Timeline.js
src/lib/lines/HorizontalLines.js

fix y calculation if line height != header height

---

src/lib/Timeline.js

and add e.preventDefault() for zooming with the ALT modifier key

refactor modifier+wheel zooming logic

---

demo/app/index.js
demo/app/styles.scss
package.json
yarn.lock

so it would be easier to link to specific demos

routes in demo

---

README.md
demo/app/demo-element-resize/index.js
demo/app/index.js
src/lib/Timeline.scss
src/resize-detector/container.js

This fixes #114 and potentially #39

Make container resize detector respond only to width changes

---

README.md

Add notice for modern module bundlers

---

src/lib/Timeline.js
src/lib/utils.js

groupHeights and groupTops in the correct type

---

src/lib/__tests__/index.js

a simple test to make sure that the plugin gets passed the props that we're expecting

test to check that plugin gets the right props

---

src/lib/Timeline.js

Fixes https://github.com/namespace-ee/react-calendar-timeline/issues/182

Issue 182 - Fix issue with drag not ending if you mouse leave scroll component

---

README.md

https://github.com/namespace-ee/react-calendar-timeline/issues/179

Issue 179: Add CodeSandbox link to Readme

---

README.md

https://github.com/namespace-ee/react-calendar-timeline/issues/178

Update link to demo in Readme

---

.gitignore
package.json
src/lib/Timeline.js
src/lib/__tests__/utils/calculate-dimesions.js
src/lib/__tests__/utils/calendar/calculate-dimensions.js
src/lib/__tests__/utils/calendar/collision.js
src/lib/__tests__/utils/calendar/coordinate-to-time-ratio.js
src/lib/__tests__/utils/calendar/get-group-orders.js
src/lib/__tests__/utils/calendar/get-grouped-items.js
src/lib/__tests__/utils/calendar/get-min-unit.js
src/lib/__tests__/utils/calendar/get-next-unit.js
src/lib/__tests__/utils/calendar/get-visible-items.js
src/lib/__tests__/utils/calendar/iterate-times.js
src/lib/__tests__/utils/calendar/no-stack.js
src/lib/__tests__/utils/calendar/stack.js
src/lib/__tests__/utils/dom-helpers/get-parent-position.js
src/lib/__tests__/utils/dom-helpers/has-same-parent-class.js
src/lib/items/Item.js
src/lib/items/Items.js
src/lib/layout/Header.js
src/lib/layout/Sidebar.js
src/lib/lines/VerticalLines.js
src/lib/test-utility/index.js
src/lib/utility/calendar.js
src/lib/utility/dom-helpers.js
src/lib/utility/generic.js
yarn.lock

* split utility methods out into category files
* wrote some tests for utility methods
* added comments for getMinUnit as this is a pretty important function
* wrote happy path tests for getMinUnit
* stubbed unit tests for all utility methods

Test coverage and refactor of tests

---

CHANGELOG.md
src/lib/layout/Header.js

https://github.com/namespace-ee/react-calendar-timeline/issues/193

193 - removed href from header div

---

CHANGELOG.md
demo/app/demo-main/index.js
src/lib/Timeline.js

https://github.com/namespace-ee/react-calendar-timeline/issues/225

Fix where context click calls double click

---

src/lib/Timeline.js
src/lib/items/Item.js

This is a proposed fix for the [issue](https://github.com/namespace-ee/react-calendar-timeline/issues/173) I opened up. I've ran the tests and linting. Everything passes. I'm still new to contributing to github projects so please let me know if I did anything wrong.

Fix for Issue 173 - Changed location of time delta check

---

CHANGELOG.md
README.md
src/lib/Timeline.js
src/lib/__tests__/utils/calendar/calculate-dimensions.js
src/lib/__tests__/utils/calendar/calculate-x-position-for-time.js
src/lib/items/Item.js
src/lib/utility/calendar.js

https://github.com/namespace-ee/react-calendar-timeline/issues/233
Current todo:

Pass canvas context to ItemRenderer

---

CHANGELOG.md
README.md
src/lib/Timeline.js

https://github.com/namespace-ee/react-calendar-timeline/issues/248

248 - onZoom callback

---

.babelrc
demo/app/demo-main/index.js
package.json
src/lib/ScrollElement.js
src/lib/Timeline.js
src/lib/__tests__/components/Header/Header.test.js
src/lib/__tests__/components/ScrollElement/ScrollElement.test.js
src/lib/__tests__/utils/calendar/get-min-unit.js
src/lib/default-config.js
src/lib/layout/Header.js
src/lib/scroll/ScrollElement.js
src/lib/test-utility/index.js
webpack.config.js
yarn.lock

* pulled ScrollElement into own component. Wrote tests
* factored out default values into separate file

Timeline refactor - ScrollElement, config files

---

CHANGELOG.md
src/lib/items/Item.js

https://github.com/namespace-ee/react-calendar-timeline/issues/277

Remove preventDefault call on Item doubleClick event

---

CHANGELOG.md
README.md
src/lib/Timeline.js
src/lib/items/Item.js
src/lib/items/Items.js

https://github.com/namespace-ee/react-calendar-timeline/issues/284

Hide item content of small items

---

src/lib/Timeline.js

Fixes #281 - more robust handling of Shift+Scroll

---

CHANGELOG.md
README.md
demo/index.js
src/lib/Timeline.js
webpack.config.js

https://github.com/namespace-ee/react-calendar-timeline/issues/274

Removed scss import from library code.

---

README.md

If someone is going to copy and past (like me), its not going to work, and this uniq letter is not easy to find!!!!!!

Fixing the very small mistake on README

---

CHANGELOG.md
src/lib/Timeline.js

https://github.com/namespace-ee/react-calendar-timeline/issues/312

Fixed issue with onCanvasClick not being called

---

CHANGELOG.md
README.md
__tests__/components/Timeline/Timeline.test.js
src/lib/Timeline.js

Related: https://github.com/namespace-ee/react-calendar-timeline/issues/299

Visible or Default time required

---

CHANGELOG.md
src/lib/Timeline.js
src/lib/scroll/ScrollElement.js

https://github.com/namespace-ee/react-calendar-timeline/issues/168

Fix - Tap on canvas dispatches onCanvasClick

---

__tests__/components/Header/Header.test.js
src/lib/layout/TimelineElementsHeader.js

#362 
add subheaderLabelFormat and headerLabelFormat  to SCU

add subheaderLabelFormat and headerLabelFormat  to SCU

---

src/lib/Timeline.js

#377 
Provide an overview of the changes in this PR.

fix grouprenderer not affecting right sidebar

---

src/lib/utility/calendar.js

#379
Provide an overview of the changes in this PR.

fix cursor marker wrong date bug

---

src/lib/Timeline.scss

Just a small cleanup during work on my implementation, nothing fancy.

Remove duplicated CSS property in 'rct-item-content'

---

README.md

Link to issue this PR addresses.  If no issue exists, please provide reasoning for PR.
Provide an overview of the changes in this PR.

wrong prop name in readme

---

package.json

#455 #451 
The peer dependencies are incorrect and we rely on React 16.3.

Update package.json peer dependencies to include React 16.3

---

src/lib/utility/calendar.js

Reverts namespace-ee/react-calendar-timeline#458

Revert "Fix to force re-render on zoom change"

---

CHANGELOG.md
__tests__/utils/calendar/calculate-scroll-canvas.js
package.json
src/lib/utility/calendar.js

#458 
fix bug where item dimensions do not update on zoom

fix item dimensions while zoom not updating

---

src/lib/utility/calendar.js

revert use memo in calendar util

---

src/lib/items/Item.js

#484 
Checks canMove on initial interact mount.

#484 Add check to if item can be moved

---

CHANGELOG.md
README.md
__tests__/components/Headers/DateHeader.test.js
src/lib/default-config.js

add default label formats for week

---

CHANGELOG.md
src/lib/scroll/ScrollElement.js

#541 
fix wheel error on chrom 73

Chrome 73 Treats Document Level Wheel/Mousewheel Event Listeners as Passive

---

package.json
src/lib/Timeline.js

[`#528`](https://github.com/namespace-ee/react-calendar-timeline/issues/528)
In a scaled the browser, for example to 75%, the screen keeps moving to the left in some case. This issue is caused by the value passed back from`onscroll` callback is decimal in a scaled browser. Then when we `// Check the scroll is correct` in componenDidUpdate, we compare that decimal number with an integer value, which is always not equal, and manually 'scroll', then causes an infinite loop.
The fix is that wrapping the 'to be compared `scrollLeft` variable'  with a Math.round(), which prevent the loop when a decimal value is set to `scrollLeft`.
Please re-edit the file 'demo/app/demo-main/index.js' with the following code. And the 'auto-scroll' bug can be triggered in a …

Fixed the auto-scroll right bug in a scaled browser.

---

CHANGELOG.md
package.json
src/lib/Timeline.js
src/lib/headers/SidebarHeader.js
src/lib/headers/TimelineHeaders.js

#607 
Add secret keys to compare children with component 
please refer to this docs for context
https://github.com/gaearon/react-hot-loader#checking-element-types

fix react-hot-loader not working with the package

---

package.json
src/lib/Timeline.scss
src/lib/rows/GroupRow.js
src/lib/rows/Rows.js

[row renderer] fix horizontal line styles

---

src/lib/timeline/TimelineStateContext.js

Link to issue this PR addresses.  If no issue exists, please provide reasoning for PR.
Provide an overview of the changes in this PR.

removed duplicated prop-types
